# File: action.yml
name: "Merly Mentor Check"
description: "Install MPCC Universal and run MerlyMentor checks on your repository"  # ≤125 chars
branding:
  icon: "rocket"
  color: "blue"

inputs:
  mm-key:
    description: "Merly API key (set as repo secret MM_KEY)"
    required: true
  install-dir:
    description: "Directory to install MPCC Universal into"
    required: false
    default: "merly-install"
  fetch-depth:
    description: "Commits to fetch for parent lookup (1, 2, or 0 for full history)"
    required: false
    default: "2"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Install MPCC Universal (staging)
      run: |
        echo "::add-mask::${{ inputs.mm-key }}"
        mkdir -p "${{ inputs.install-dir }}"
        cd "${{ inputs.install-dir }}"
        curl -fsSL https://raw.githubusercontent.com/merly-ai/MPCC-Universal/main/install.sh \
          | bash -s -- -q -k "${{ inputs.mm-key }}" install --staging

    - name: Run MerlyMentor
      run: |
        echo "::add-mask::${{ inputs.mm-key }}"
        cd "${{ inputs.install-dir }}"
        ./MerlyMentor-Staging --github-actions -D "${GITHUB_WORKSPACE}" check
