# File: action.yml
name: "Merly Mentor Check"
description: "Runs MerlyMentor inside Docker against your repository."
branding:
  icon: "rocket"
  color: "blue"

inputs:
  mm-key:
    description: "Merly API key (store as repo secret MM_KEY)"
    required: true
  model-path:
    description: "Path inside container to mount your models directory"
    required: false
    default: "/data/.models/"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Run MerlyMentor in Docker
      shell: bash
      run: |
        docker run --rm \
          -e REGISTRATION_KEY="${{ inputs.mm-key }}" \
          -e REPO="/repo" \
          -e mm_models_root="${{ inputs.model-path }}" \
          -v "${{ github.workspace }}:/repo" \
          merlyai/mentor:gh_action_v0.0.3 -D /repo --github-actions check
