# File: action.yml
name: "Merly Mentor Check"
description: "Runs MerlyMentor inside Docker against your repository."
branding:
  icon: check-circle
  color: white

inputs:
  mm-key:
    description: "Merly API key (store as repo secret MM_KEY)"
    required: false
  checkout-code:
    description: "Do a checkout in the action"
    required: false
    default: true
  path:
    description: "The path of the repository as defined by your checkout if it is custom"
    required: false
    default: ${{ github.workspace }}
  debug:
    description: "Turn on debug logs for Mentor"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout-code == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Run MerlyMentor in Docker
      shell: bash
      run: |
        docker run --rm \
          -e REGISTRATION_KEY="${{ inputs.mm-key }}" \
          -e REPO="/repo" \
          -e mm_models_root="/data/.models/" \
          -v "${{ inputs.path }}:/repo" \
          merlyai/mentor:gh_action_v0.0.3 -D /repo --github-actions check ${{ inputs.debug == 'true' && '--debug --stdout' || '' }}

