name: Release on Tag

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'  # semver tags like v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tag and version info
        id: versioning
        run: |
          echo "TAG=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          MAJOR=$(echo "${GITHUB_REF_NAME}" | sed -E 's/^v([0-9]+).*/\1/')
          echo "MAJOR_VERSION=$MAJOR" >> "$GITHUB_ENV"
          echo "RELEASE_NAME=release-$MAJOR" >> "$GITHUB_ENV"

      - name: Template README.md
        run: |
          sed "s/{{TAG}}/${TAG}/g" templates/README.md > README.md

      - name: Template action.yaml
        run: |
          sed "s/{{TAG}}/${TAG}/g" templates/action.yaml > action.yaml

      - name: Debug workspace
        run: |
          ls -la

      - name: Commit and push README.md and action.yaml to the repo
        run: |
          # Commit the generated files to the root of the repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md action.yaml
          git commit -m "Add action.yaml and README.md for release ${TAG}"
          git push origin HEAD:${GITHUB_REF_NAME}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name:     ${{ env.RELEASE_NAME }}
          files: |
            action.yaml
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
